name: LaTex2PDF

on:
  push:
    branches:
      - timestamped-version
    paths:
      - 'latexResume/resume.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: latexResume/resume
      LATEX: pdflatex
    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: Cache LaTeX dependencies
      uses: actions/cache@v4
      with:
        path: /usr/share/texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('latexResume/resume.tex') }}
        restore-keys: |
          ${{ runner.os }}-texlive-
    
    - name: Install texlive
      if: steps.cache-latex.outputs.cache-hit != 'true'
      run: |
            sudo apt-get install texlive-publishers \
                                 texlive-latex-recommended \
                                 texlive-latex-extra \
                                 texlive-fonts-recommended \
                                 texlive-fonts-extra
    
    - name: Build resume
      run: |
            cd ${MANUSCRIPT_PATH%/*}
            TIMESTAMP=$(date +%Y-%m-%d--%H-%M-%S)
            ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
            cp ${MANUSCRIPT_PATH##*/}.pdf ${MANUSCRIPT_PATH##*/}_latest.pdf
            mv ${MANUSCRIPT_PATH##*/}.pdf ${MANUSCRIPT_PATH##*/}_$TIMESTAMP.pdf
            echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
                               
    - name: Push resume
      run: |
            cd ${MANUSCRIPT_PATH%/*}
            git add -f ${MANUSCRIPT_PATH##*/}_latest.pdf
            git add -f ${MANUSCRIPT_PATH##*/}_$TIMESTAMP.pdf
            git -c user.name='resume-maker' -c user.email='resume-maker' commit -m "update pdf"
            git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    
    - name: Cache ImageMagick and Ghostscript
      uses: actions/cache@v4
      with:
        path: |
          /usr/bin/convert
          /usr/bin/gs
        key: ${{ runner.os }}-imagemagick-ghostscript
    
    - name: Install ghostscript
      if: steps.cache-imagemagick.outputs.cache-hit != 'true'
      run: sudo apt-get update --fix-missing && sudo apt install ghostscript
    
    # Rest of the steps remain the same